### ISSUE TITLE
regression test

### ISSUE THREAD

**Issue by jochun86** [mdolab/dafoam#12]
I got an error in regression test after installation.

The error message is like below.
_ImportError: No module named regression_helper_

so current reg_test folder need to be added to the pythonpath

please run below command, before run the test.
_export PYTHONPATH=$PYTHONPATH:$HOME/repos/dafoam/python/reg_tests_

I think the documentation also needs to be updated :)

currently my reg_test is still running and I hope to be finished with OK.

**Comment by friedenhe** [comment]
Thanks for the feedback. 

This is strange because regression_helper.py and run_reg_tests.py are in the same folder, so you shouldn't need to manually import regression_helper when running the run_reg_tests.py script.

I updated the doc/installation page and gave suggestions for the folder structures and environmental variable setup. Please check if these are properly set. 

Also, I strongly recommend using the pre-compiled package (see the doc/download page) to get familiar with the DAFoam environment and setup.

Good luck!

Thanks,
Ping
